// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: activities.sql

package pg

import (
	"context"
)

const addActivity = `-- name: AddActivity :exec
insert into activities
(class_name, title, timestamp)
values ($1, $2, now())
`

type AddActivityParams struct {
	ClassName string
	Title     string
}

func (q *Queries) AddActivity(ctx context.Context, arg AddActivityParams) error {
	_, err := q.db.Exec(ctx, addActivity, arg.ClassName, arg.Title)
	return err
}
